name: Create Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Create Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Upload Assests Asset
        id: upload-tar-asset
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "dist/*.tar.gz;dist/*.whl"
          repo-token: ${{ secrets.GITHUB_TOKEN }}